travis:
  secure:
    BINSTAR_TOKEN: baoKDtgOqp+qfdLJvt8XXY+cM2ovn1/x1PKOYcKf5CaUlkbyEtfSL2aCRHqIq0a7g9zUcbynuhm9xoZIipuAXeUBILJPiaKpfhWUdW3qk8jWn13nEE6hHcPn0HCj/R8dhB8Dz3I8/6YZaTZIdrPzixbRo9C9ClhIB5aaZDzA6XugUreB70bwaEoamK7cOx0ALiiZ2eR7bhTWSC3O0J5XkyATjbVbssweX7I0j4you+ac3I41K1Sm7PNOIduNIC18FJnkbjtAjXqTC98dP3T0jOh3Lncbq5Xv/noHcX113tNBJ21P6BygRe2fjCwOCad0Aui+qeRzxe7mqROyjps0xJeU5jD7aFfO9Z5r1m18vY/MQF8VpLK22x7aNZ7zPGcTlZiwtjNNcE86yh7j9lm2w1ou1G9XqnDusY4KkhWfxWDsawVnVA7u5QDdPv7qN67ctUbcIfD/S2vhnFwOK2LuYYWYLhoCZvW9OXArJaV3U1xak7R0bRKXL/VXJmYrOhC81gqCQFqcOgCX5MtiAD/gPzaUGcIDLTC/ALLoWHWdO6cLIngkIXBpmNCLNnoaC3inqyFncQNh9dfy+Axe6D1pFH8kKtYUDhjoOBtKiLCQATcsynWw4q1+sYENdKBIAhCDkQ+u7TNDcx3szAiUGsncbzcnusp1jZze8+uB9k7H9Mw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
