travis:
  secure:
    BINSTAR_TOKEN: du7ax4EIkmnaznP2+jIh8Q5PTeI19cWMS603pIlczBbk+496ROfqi9JTHvIyF0BzZtZ8TTgC8t4H/2p5kqUtbuA6ENHlTYGQ4z9TUjy386wVbx+UX7sF7PMO/niN3s+zaQhnsIE0mzo7ESVG2M8CJ/qXzNeoJGUBU9VIOPJ/wgw+M24JY0W7swGcr07wtvIJb/4BirRLsu3hRWKyOugE+MuqnjHlmFrdA9Sxy/iu3OsVn6pBEGA7iB7cnXDzL2cTDsVotIEIF83Omq5DVsYuO0SshBNdbokmUzVznrW7+9Cepu897Od2HkIksylGwwbSxcer0NHqSUNE2+jJTaz9tUrXol+Az2GPeVDT+8/hejd0sqcqJZ0tIreXpILPPKo91spdlKnRZeyXSN4iTze1j8AFg6YPTNoyOrHa/6Ql/EcWCQm1zdnTOZA3C/Xnw6DGD6SCxNsCkQiexh8JQ2aexcWACx4MHqbqO1XA9Wnlt/CwmU3NeRf6cxreKgM/eo8fs/BehgFb4+csh+1CEtgRPyt7MScFFc+tbxS86+Tvs8xOlvSFf21z9GXtinMOdI+vhKDM+SLw8HEB8hjBYGKWr16osJBKE0LDI9AZnghv0llGAVqkcBL+5R6c8tlh951XSBIqrMXF7Tt6A4vZi2AsqMXpySMux8kum+PoJoF8Eu0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
